[package]
name = "binance-futures"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam-queue = "0.3"
crossterm = "0.29"
ratatui = "0.29"
serde_json = "1.0"
tungstenite = "0.26.2"
url = "2.4"
ordered-float = "5.0.0"
parking_lot = "0.12"
reqwest = { version = "0.12", features = ["json"] }