[package]
name = "binance-futures"
version = "0.1.0"
edition = "2021"

[dependencies]
tungstenite = { version = "0.24", features = ["native-tls"] }
url = "2.5"
serde_json = "1.0"
crossterm = "0.28"
ratatui = "0.29"
ordered-float = "4.5"
env_logger = "0.11"