[package]
name = "binance-futures"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1.19"
tungstenite = { version = "0.24", features = ["native-tls"] }
url = "2.5"
core_affinity = "0.8"
crossterm = "0.28"
ratatui = "0.29"
ordered-float = "4.5"
env_logger = "0.11"
serde_json = "1.0"