# Binance REST API Provider Configuration
# Market data and trading via REST API

[provider]
# Provider identification - MUST match config.toml
name = "binance_rest"       # Matches config.toml exactly
type = "BinanceRest"        # Matches config.toml exactly
version = "1.0.0"

[connection]
# REST API connection settings
base_url = "https://fapi.binance.com"
testnet_url = "https://testnet.binancefuture.com"
use_testnet = false
timeout = 30000  # milliseconds
max_retries = 3
retry_delay = 1000  # milliseconds

[authentication]
# API credentials (required for private endpoints)
api_key = ""
api_secret = ""
use_signature = true  # Enable request signing

[rate_limiting]
# Rate limit configuration
enabled = true
requests_per_minute = 2400  # Binance limit
requests_per_second = 20
order_requests_per_second = 10
weight_limit = 6000  # Request weight limit per minute

[endpoints]
# Endpoint configuration
klines_endpoint = "/fapi/v1/klines"
ticker_endpoint = "/fapi/v1/ticker/24hr"
depth_endpoint = "/fapi/v1/depth"
trades_endpoint = "/fapi/v1/trades"
account_endpoint = "/fapi/v2/account"
order_endpoint = "/fapi/v1/order"

[market_data]
# Market data settings
symbols = ["BTCFDUSD", "ETHFDUSD"]
default_limit = 500  # Default number of records
kline_interval = "1m"  # 1m, 3m, 5m, 15m, 30m, 1h, 2h, 4h, 6h, 8h, 12h, 1d, 3d, 1w, 1M
depth_limit = 20  # Order book depth

[caching]
# Response caching
enabled = true
cache_duration = 1000  # milliseconds
cache_size = 100  # Number of cached responses
cache_market_data = true
cache_account_data = false

[error_handling]
# Error handling
on_rate_limit = "wait"  # wait, skip, error
on_network_error = "retry"  # retry, skip, error
log_errors = true
propagate_errors = false

[logging]
# Provider-specific logging
log_level = "info"
log_requests = false
log_responses = false
log_performance = true