# Gzip Historical Data Provider Configuration
# Reads compressed historical market data from .gz files

# 数据目录路径
data_dir = "./data"

# 文件名模式
file_pattern = "*.gz"

# 符号过滤（可选）
# symbol_filter = "BTCFDUSD"

# 事件类型过滤
event_filter = []

[playback_config]
# 初始播放速度倍数
initial_speed = 10.0
# 是否自动开始播放
auto_start = true
# 是否循环播放
loop_enabled = false
# 最大播放速度
max_speed = 1000.0
# 最小播放速度
min_speed = 0.1
# 时间过滤（可选）
# start_timestamp = 0
# end_timestamp = 0

# 虚拟时钟配置
# 是否启用纳秒级精度（false时使用微秒精度以提高性能）
nanosecond_precision = true
# 时间漂移容差（纳秒）- 允许的时间误差范围，默认1ms
drift_tolerance_ns = 1000000

[buffer_config]
# 事件缓冲区大小
event_buffer_size = 10000
# 预读取行数
prefetch_lines = 1000
# 内存限制（MB）
memory_limit_mb = 500
